# Generated by Django 2.2 on 2022-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.FileField(upload_to='pic')),
                ('desc', models.TextField()),
            ],
        ),
    ]
